"use client";

import { useState } from "react";
import Link from "next/link";
import { useKnowledge } from "@/components/knowledge-store";
import { CheckCircleIcon, PlusIcon } from "@/components/icons";
import type { Client, Decision, Document, Person, Project, Topic } from "@/lib/knowledge";

const kinds = ["client", "person", "project", "topic", "decision", "document"] as const;
type Kind = (typeof kinds)[number];
type Saved = { kind: Kind; id: string; label: string };
const inputClass = "h-11 w-full rounded-xl border border-slate-300 bg-white px-3.5 font-normal outline-none transition focus:border-teal-500 focus:ring-2 focus:ring-teal-500/20";
const labels: Record<Kind, string> = { client: "Client", person: "Person", project: "Project", topic: "Topic", decision: "Decision", document: "Document / Note" };

export function ManageView({ editKind, editId }: { editKind?: Kind; editId?: string }) {
  const store = useKnowledge();
  const [kind, setKind] = useState<Kind>(editKind ?? "decision");
  const [saved, setSaved] = useState<Saved | null>(null);
  const initial = editKind && editId ? findInitial(editKind, editId, store.collections) : undefined;
  const done = (item: Saved) => setSaved(item);
  const remove = (item: Saved) => { store.removeEntity(item.kind, item.id); done(item); };

  return <div className="mx-auto w-full max-w-4xl">
    <p className="inline-flex items-center gap-1.5 rounded-full bg-teal-50 px-3 py-1 text-xs font-semibold uppercase tracking-[0.14em] text-teal-700 ring-1 ring-teal-100"><PlusIcon className="h-3.5 w-3.5" />Add / Edit</p>
    <h1 className="mt-3 text-2xl font-bold tracking-tight sm:text-3xl">Manage knowledge</h1>
    <p className="mt-2 max-w-2xl text-base leading-7 text-slate-600">Create, update, or remove clients, people, projects, topics, decisions, and documents. Linked records update the knowledge graph immediately.</p>
    <div className="mt-6 flex flex-wrap gap-1 rounded-xl border border-slate-200 bg-white p-1 shadow-sm">
      {kinds.map((item) => <button key={item} onClick={() => { setKind(item); setSaved(null); }} className={`rounded-lg px-3 py-2 text-sm font-semibold transition ${kind === item ? "bg-slate-950 text-white shadow-sm" : "text-slate-600 hover:bg-slate-50"}`}>Add {labels[item]}</button>)}
    </div>
    {saved ? <SavedNotice saved={saved} onMore={() => setSaved(null)} /> : <Editor kind={kind} initial={initial} onSave={done} onDelete={initial ? () => remove({ kind: editKind!, id: editId!, label: labelOf(initial) }) : undefined} />}
  </div>;
}

function SavedNotice({ saved, onMore }: { saved: Saved; onMore: () => void }) {
  return <div className="mt-6 rounded-2xl border border-teal-200 bg-teal-50 p-6 shadow-sm"><div className="flex gap-3"><CheckCircleIcon className="mt-0.5 h-6 w-6 shrink-0 text-teal-600" /><div><p className="font-semibold text-teal-900">Saved “{saved.label}”.</p><p className="mt-1 text-sm text-teal-800">Its connected knowledge is now updated.</p></div></div><div className="mt-4 flex flex-wrap gap-3"><Link href={`/knowledge?type=${saved.kind}&id=${saved.id}`} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">View in Knowledge</Link><button onClick={onMore} className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold">Add another</button></div></div>;
}

function Editor({ kind, initial, onSave, onDelete }: { kind: Kind; initial?: Client | Person | Project | Topic | Decision | Document; onSave: (saved: Saved) => void; onDelete?: () => void }) {
  const store = useKnowledge();
  if (kind === "client") return <ClientForm initial={initial as Client | undefined} onSave={(item) => { store.upsertClient(item); onSave({ kind, id: item.id, label: item.name }); }} onDelete={onDelete} />;
  if (kind === "person") return <PersonForm initial={initial as Person | undefined} onSave={(item) => { store.upsertPerson(item); onSave({ kind, id: item.id, label: item.name }); }} onDelete={onDelete} />;
  if (kind === "topic") return <TopicForm initial={initial as Topic | undefined} onSave={(item) => { store.upsertTopic(item); onSave({ kind, id: item.id, label: item.name }); }} onDelete={onDelete} />;
  if (kind === "project") return <ProjectForm initial={initial as Project | undefined} clients={store.collections.clients} people={store.collections.people} topics={store.collections.topics} onSave={(item) => { store.upsertProject(item); onSave({ kind, id: item.id, label: item.name }); }} onDelete={onDelete} />;
  if (kind === "decision") return <DecisionForm initial={initial as Decision | undefined} projects={store.collections.projects} people={store.collections.people} topics={store.collections.topics} onSave={(item) => { store.upsertDecision(item); onSave({ kind, id: item.id, label: item.title }); }} onDelete={onDelete} />;
  return <DocumentForm initial={initial as Document | undefined} projects={store.collections.projects} topics={store.collections.topics} onSave={(item) => { store.upsertDocument(item); onSave({ kind, id: item.id, label: item.label }); }} onDelete={onDelete} />;
}

function ClientForm({ initial, onSave, onDelete }: FormProps<Client>) { const [name, setName] = useState(initial?.name ?? ""); const [industry, setIndustry] = useState(initial?.industry ?? ""); const [size, setSize] = useState(initial?.size ?? ""); const [contact, setContact] = useState(initial?.primary_contact ?? ""); const [status, setStatus] = useState(initial?.status ?? "Active"); const [notes, setNotes] = useState(initial?.notes ?? ""); return <Form onSubmit={() => onSave({ id: initial?.id ?? makeId("client"), name, industry, size, primary_contact: contact, status, notes })} onDelete={onDelete}><Field label="Client name" value={name} setValue={setName} required /><div className="grid gap-5 md:grid-cols-2"><Field label="Industry" value={industry} setValue={setIndustry} /><Field label="Size" value={size} setValue={setSize} /></div><div className="grid gap-5 md:grid-cols-2"><Field label="Primary contact" value={contact} setValue={setContact} /><Field label="Status" value={status} setValue={setStatus} /></div><Area label="Notes" value={notes} setValue={setNotes} /></Form>; }
function PersonForm({ initial, onSave, onDelete }: FormProps<Person>) { const [name, setName] = useState(initial?.name ?? ""); const [role, setRole] = useState(initial?.role ?? ""); const [email, setEmail] = useState(initial?.email ?? ""); const [skills, setSkills] = useState(initial?.skills.join(", ") ?? ""); return <Form onSubmit={() => onSave({ id: initial?.id ?? makeId("person"), name, role, email, skills: split(skills) })} onDelete={onDelete}><Field label="Full name" value={name} setValue={setName} required /><div className="grid gap-5 md:grid-cols-2"><Field label="Role" value={role} setValue={setRole} /><Field label="Email" value={email} setValue={setEmail} type="email" /></div><Field label="Skills (comma separated)" value={skills} setValue={setSkills} /></Form>; }
function TopicForm({ initial, onSave, onDelete }: FormProps<Topic>) { const [name, setName] = useState(initial?.name ?? ""); const [description, setDescription] = useState(initial?.description ?? ""); return <Form onSubmit={() => onSave({ id: initial?.id ?? makeId("topic"), name, description })} onDelete={onDelete}><Field label="Topic name" value={name} setValue={setName} required /><Area label="Description" value={description} setValue={setDescription} /></Form>; }
function ProjectForm({ initial, clients, people, topics, onSave, onDelete }: FormProps<Project> & { clients: Client[]; people: Person[]; topics: Topic[] }) { const [name, setName] = useState(initial?.name ?? ""); const [clientId, setClientId] = useState(initial?.client_id ?? ""); const [status, setStatus] = useState(initial?.status ?? "In Progress"); const [start, setStart] = useState(initial?.start_date ?? new Date().toISOString().slice(0, 10)); const [end, setEnd] = useState(initial?.end_date ?? ""); const [lead, setLead] = useState(initial?.lead ?? people[0]?.id ?? ""); const [team, setTeam] = useState(initial?.team ?? []); const [topicNames, setTopicNames] = useState(initial?.key_topics ?? []); const [description, setDescription] = useState(initial?.description ?? ""); return <Form onSubmit={() => onSave({ id: initial?.id ?? makeId("project"), name, client_id: clientId || null, status, start_date: start, ...(end ? { end_date: end } : {}), lead, team, key_topics: topicNames, description })} onDelete={onDelete}><Field label="Project name" value={name} setValue={setName} required /><Area label="Description" value={description} setValue={setDescription} /><div className="grid gap-5 md:grid-cols-2"><Select label="Client" value={clientId} setValue={setClientId} items={clients.map((item) => ({ id: item.id, label: item.name }))} empty="Internal project" /><Field label="Status" value={status} setValue={setStatus} /></div><div className="grid gap-5 md:grid-cols-2"><Field label="Start date" value={start} setValue={setStart} type="date" /><Field label="End date" value={end} setValue={setEnd} type="date" /></div><Select label="Project lead" value={lead} setValue={setLead} items={people.map((item) => ({ id: item.id, label: item.name }))} /><Checks legend="Team members" items={people.map((item) => ({ id: item.id, label: item.name }))} selected={team} setSelected={setTeam} /><Checks legend="Key topics" items={topics.map((item) => ({ id: item.name, label: item.name }))} selected={topicNames} setSelected={setTopicNames} /></Form>; }
function DecisionForm({ initial, projects, people, topics, onSave, onDelete }: FormProps<Decision> & { projects: Project[]; people: Person[]; topics: Topic[] }) { const [title, setTitle] = useState(initial?.title ?? ""); const [summary, setSummary] = useState(initial?.summary ?? ""); const [projectId, setProjectId] = useState(initial?.project_id ?? ""); const [madeBy, setMadeBy] = useState(initial?.made_by ?? people[0]?.id ?? ""); const [participants, setParticipants] = useState(initial?.participants ?? []); const [topicNames, setTopicNames] = useState(initial?.related_topics ?? []); return <Form onSubmit={() => onSave({ id: initial?.id ?? makeId("decision"), title, date: initial?.date ?? new Date().toISOString().slice(0, 10), project_id: projectId || null, made_by: madeBy, participants, summary, related_topics: topicNames })} onDelete={onDelete}><Field label="Decision title" value={title} setValue={setTitle} required /><Area label="Reasoning / summary" value={summary} setValue={setSummary} /><div className="grid gap-5 md:grid-cols-2"><Select label="Project" value={projectId} setValue={setProjectId} items={projects.map((item) => ({ id: item.id, label: item.name }))} empty="None (internal)" /><Select label="Made by" value={madeBy} setValue={setMadeBy} items={people.map((item) => ({ id: item.id, label: item.name }))} /></div><Checks legend="People involved" items={people.map((item) => ({ id: item.id, label: item.name }))} selected={participants} setSelected={setParticipants} /><Checks legend="Related topics" items={topics.map((item) => ({ id: item.name, label: item.name }))} selected={topicNames} setSelected={setTopicNames} /></Form>; }
function DocumentForm({ initial, projects, topics, onSave, onDelete }: FormProps<Document> & { projects: Project[]; topics: Topic[] }) { const [label, setLabel] = useState(initial?.label ?? ""); const [summary, setSummary] = useState(initial?.summary ?? ""); const [projectIds, setProjectIds] = useState(initial?.projects ?? []); const [topicNames, setTopicNames] = useState(initial?.topics ?? []); return <Form onSubmit={() => onSave({ id: initial?.id ?? makeId("document"), label, summary, projects: projectIds, topics: topicNames })} onDelete={onDelete}><Field label="Title / name" value={label} setValue={setLabel} required /><Area label="Summary / note" value={summary} setValue={setSummary} /><Checks legend="Related projects" items={projects.map((item) => ({ id: item.id, label: item.name }))} selected={projectIds} setSelected={setProjectIds} /><Checks legend="Related topics" items={topics.map((item) => ({ id: item.name, label: item.name }))} selected={topicNames} setSelected={setTopicNames} /></Form>; }

type FormProps<T> = { initial?: T; onSave: (item: T) => void; onDelete?: () => void };
function Form({ children, onSubmit, onDelete }: { children: React.ReactNode; onSubmit: () => void; onDelete?: () => void }) { return <form className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6" onSubmit={(event) => { event.preventDefault(); onSubmit(); }}><div className="grid gap-5">{children}<div className="flex flex-wrap gap-3"><button className="h-11 rounded-xl bg-slate-950 px-5 text-sm font-semibold text-white">Save changes</button>{onDelete ? <button type="button" onClick={onDelete} className="h-11 rounded-xl border border-rose-300 px-5 text-sm font-semibold text-rose-700">Delete</button> : null}</div></div></form>; }
function Field({ label, value, setValue, required, type = "text" }: { label: string; value: string; setValue: (value: string) => void; required?: boolean; type?: string }) { return <label className="grid gap-2 text-sm font-semibold">{label}<input required={required} type={type} value={value} onChange={(event) => setValue(event.target.value)} className={inputClass} /></label>; }
function Area({ label, value, setValue }: { label: string; value: string; setValue: (value: string) => void }) { return <label className="grid gap-2 text-sm font-semibold">{label}<textarea value={value} onChange={(event) => setValue(event.target.value)} rows={4} className="w-full resize-none rounded-xl border border-slate-300 p-3.5 font-normal leading-7 outline-none focus:border-teal-500" /></label>; }
function Select({ label, value, setValue, items, empty }: { label: string; value: string; setValue: (value: string) => void; items: { id: string; label: string }[]; empty?: string }) { return <label className="grid gap-2 text-sm font-semibold">{label}<select value={value} onChange={(event) => setValue(event.target.value)} className={inputClass}>{empty ? <option value="">{empty}</option> : null}{items.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label>; }
function Checks({ legend, items, selected, setSelected }: { legend: string; items: { id: string; label: string }[]; selected: string[]; setSelected: (items: string[]) => void }) { return <fieldset className="rounded-xl border border-slate-200 p-4"><legend className="px-2 text-sm font-semibold">{legend}</legend><div className="grid gap-2 sm:grid-cols-2">{items.map((item) => <label key={item.id} className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm"><input type="checkbox" checked={selected.includes(item.id)} onChange={() => setSelected(selected.includes(item.id) ? selected.filter((id) => id !== item.id) : [...selected, item.id])} className="accent-teal-600" />{item.label}</label>)}</div></fieldset>; }
function makeId(prefix: string) { return `${prefix}-${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`; }
function split(value: string) { return value.split(",").map((item) => item.trim()).filter(Boolean); }
function labelOf(item: Client | Person | Project | Topic | Decision | Document) { return "name" in item ? item.name : "title" in item ? item.title : item.label; }
function findInitial(kind: Kind, id: string, collections: ReturnType<typeof useKnowledge>["collections"]) { const map = { client: collections.clients, person: collections.people, project: collections.projects, topic: collections.topics, decision: collections.decisions, document: collections.documents }; return map[kind].find((item) => item.id === id); }
